# Generated by Django 4.0 on 2021-12-31 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='document',
        ),
        migrations.RemoveField(
            model_name='language',
            name='document',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.language'),
        ),
        migrations.AddField(
            model_name='document',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.qualification'),
        ),
    ]
