# Generated by Django 4.0 on 2021-12-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
    ]
