# Generated by Django 4.0 on 2021-12-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_rename_vacation_date_vacation_vacation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vacation_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vacation_start_date',
            field=models.DateField(null=True),
        ),
    ]
