# Generated by Django 4.0 on 2022-01-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_alter_vacation_vacation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.employee'),
        ),
    ]
