# Generated by Django 4.0 on 2022-01-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_document_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sub_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.project', verbose_name='Projects'),
        ),
    ]
