# Generated by Django 4.0 on 2022-01-05 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_alter_project_sub_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sub_project',
        ),
        migrations.AddField(
            model_name='project',
            name='top_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='archive.project', verbose_name='Top Project'),
        ),
    ]
