# Generated by Django 4.0 on 2022-01-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_remove_project_sub_project_project_top_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.project')),
            ],
        ),
    ]
