# Generated by Django 4.0 on 2022-01-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_projectdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.projectdetail'),
        ),
    ]
