# Generated by Django 4.0 on 2022-01-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_remove_projectdetail_project_project_project_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='daily_criteria',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='to_do',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
