# Generated by Django 4.0 on 2022-01-05 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_projectdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.project', verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.projectdetail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='top_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='archive.project', verbose_name='Top Project'),
        ),
    ]
